import argparse
import os
from datetime import datetime
from conf import Conf
from Observables import ObservableFactory
from runner import Runner
from results import Results
import plotting
import reporting


run_time_str = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
output_dir = f'artifacts/{run_time_str}'
os.makedirs(output_dir, exist_ok=True)

# Create Results instance with output directory
res = Results(run_time_str, output_dir)

def print_run_plan(confs):
    print('#########################################################')
    print(f'Configurations to run: {len(confs)}')
    sim_count = sum(1 for c in confs if c.run_simulator)
    # Estimate sampler runs based on presence of p_dephase (can be refined)
    sampler_noise_count = sum(1 for c in confs if c.run_sampler and getattr(c, 'p_dephase', None) is not None) # Check attribute safely
    sampler_hw_count = sum(1 for c in confs if c.run_sampler and getattr(c, 'p_dephase', None) is None) # Assuming no p_dephase means hardware or ideal sim
    print(f'  Simulator runs: {sim_count}')
    print(f'  Sampler (sim w/ noise) runs: {sampler_noise_count}')
    print(f'  Sampler (HW/noiseless sim) runs: {sampler_hw_count}')
    print('#########################################################')


def report_and_plot(results_obj: Results):
    """Generates plots and the final HTML report."""
    results_list = results_obj.processed_results # Use the processed results list
    output_dir = results_obj.output_dir
    plot_filenames = [] # Collect paths to generated plots for the report

    if not results_list:
        print("No processed results to plot or report.")
        return

    # --- Plotting ---
    file_name = plotting.plot_expectation_vs_parameter_filtered(results_list, output_dir, 'theta')
    plot_filenames.append(file_name)

    # file_name = plotting.plot_expectation_vs_parameter_filtered(results_list, output_dir, 'p_dephase')
    # file_name = plotting.plot_expectation_vs_parameter_filtered_subplots(results_list, output_dir, 'p_dephase')

    files = plotting.plot_counts_hist()
    plot_filenames.extend(files)

    file_name = plotting.plot_heatmap(results_list, output_dir)
    plot_filenames.append(file_name)

    reporting.generate_report(results_list, plot_filenames, output_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run Quantum Teleportation Simulation")

    # Allow overriding specific Conf parameters via command line
    parser.add_argument('--h-param', type=float, help="Override 'h' parameter in conf.yaml")
    parser.add_argument('--k-param', type=float, help="Override 'k' parameter in conf.yaml")
    parser.add_argument('--total-shots', type=int, help="Override 'total_shots' in conf.yaml") # Use int for shots
    # Allow running all generated configurations instead of just one
    parser.add_argument('--run-all-conf', action='store_true', help="Run all configurations generated by Conf.generate_all_confs()") # Changed to store_true

    args = parser.parse_args()

    # --- Configuration Loading ---
    confs = []
    if args.run_all_conf:
        # Generate multiple configurations based on ranges defined in Conf class
        confs = Conf.generate_all_confs()
        if not confs:
            print("Warning: generate_all_confs() returned no configurations. Check Conf class.")
            exit() # Exit if no configurations are generated
    else:
        # Load a single configuration, potentially overriding from CLI args
        conf = Conf() # Create default Conf instance
        try:
            conf.load() # Load parameters from conf.yaml
            print("Loaded configuration from conf.yaml")
        except FileNotFoundError:
            print("conf.yaml not found, using default Conf parameters.")
        except Exception as e:
            print(f"Error loading conf.yaml: {e}. Using default Conf parameters.")

        # Override specific parameters if provided via command line
        if args.h_param is not None: conf.h = args.h_param
        if args.k_param is not None: conf.k = args.k_param
        if args.total_shots is not None: conf.total_shots = args.total_shots
        confs.append(conf) # Add the single (potentially modified) config to the list

    print(f"Generated {len(confs)} configurations to run.")
    print_run_plan(confs) # Display the plan based on the configurations list
    input("Press Enter to continue...") # Optional confirmation step

    # --- Observable Setup ---
    observable_factory = ObservableFactory()

    # --- Execution Loop ---
    # Runner initialization logic can be complex depending on backend/noise model sharing.
    # This simple version re-initializes if backend or primary noise param (p_dephase) changes.
    current_runner = None

    for i, conf in enumerate(confs):
        print(f"\n--- Running Configuration {i+1}/{len(confs)} ---")
        print(conf) # Print current config

        # Create/get observables for this config (needed for runner)
        # Note: Factory creates *all* observables, runner uses the list of simulatable ones
        simulatable_obs_list = observable_factory.create_observables(conf)

        # Initialize Runner (or re-init if backend/noise changes significantly)
        # Pass only the list of observables to simulate
        runner = Runner(simulatable_obs_list)
        # Initialize backend, noise model etc. for this specific conf
        runner.init_run_level(conf, conf.backend)

        # Execute each observable for the current configuration
        for obs in simulatable_obs_list:
             runner.execute_observable(obs, conf, res)

        print(f"--- Finished Configuration {i+1}/{len(confs)} ---")


    # --- Post-Processing ---
    print("\n--- Post-Processing Results ---")
    res.process_results(observable_factory) # Calculate metrics, derive observables

    # --- Save Processed Results ---
    res.save_results("processed_results.json")

    # --- Analysis & Reporting ---
    print("\n--- Generating Plots and Report ---")
    # Load results back if needed (e.g., if running analysis separately)
    # res.load_results("processed_results.json")

    report_and_plot(res)
    print("\n--- Simulation and Analysis Complete ---")
