import argparse
import os
from datetime import datetime
from conf import Conf
from Observables import ObservableFactory
from runner import Runner
from results import Results
import plotting
import reporting


run_time_str = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
output_dir = f'artifacts/{run_time_str}'
os.makedirs(output_dir, exist_ok=True)

# Create Results instance with output directory
res = Results(run_time_str, output_dir)

def print_run_plan():
    print('#########################################################')
    print(f'sim num: {len([i for i in confs if i.run_simulator])}')
    print(f'sampler sim num: {len([i for i in confs if i.run_sampler and i.p_dephase is not None])}')
    print(f'sampler num: {len([i for i in confs if i.run_sampler and i.p_dephase is None])}')

def report_and_plot(res):
    # Generate desired plots using the plotting module
    # Example: Plot expectation value vs p_dephase for h=1, k=1 runs
    try:
        plot_filename_exp = plotting.plot_expectation_vs_parameter(
            results_list=res.processed_results,
            x_param_path='noise_params.p_dephase', # Path to parameter in RunResult
            y_param_path='expectation_value',
            error_param_path='sem',
            output_dir=res.output_dir,
            filename_prefix="exp_vs_p_dephase",
            title_prefix="Expectation Value vs Dephasing",
            group_by=['observable_name'], # Separate lines for each observable
            filter_criteria={'conf_params.h': 1.0, 'conf_params.k': 1.0} # Example filter
        )
        print(f"Generated plot: {plot_filename_exp}")

        # Example: Plot susceptibility vs h for k=1, no noise runs
        plot_filename_susceptibility = plotting.plot_expectation_vs_parameter(
            results_list=res.processed_results,
            x_param_path='conf_params.h',
            y_param_path='susceptibility',
            output_dir=res.output_dir,
            filename_prefix="susceptibility_vs_h",
            title_prefix="Susceptibility vs h (k=1, No Noise)",
            group_by=['observable_name'],
            filter_criteria={'conf_params.k': 1.0, 'noise_params': {}} # Filter for no noise
        )
        print(f"Generated plot: {plot_filename_susceptibility}")

        # ... add calls to generate other plots (counts histograms, etc.) ...
        plot_filenames = [f for f in [plot_filename_exp, plot_filename_susceptibility] if f] # Collect generated plot paths

        # Generate HTML Report
        reporting.generate_html_report(
            results_list=res.processed_results,
            plot_filenames=plot_filenames, # Pass paths to generated plots
            output_dir=res.output_dir,
            report_filename="final_report.html"
        )
        print(f"Generated report in {res.output_dir}")

    except Exception as e:
        print(f"Error during plotting/reporting: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run Quantum Teleportation Simulation")

    # Allow overriding specific Conf parameters via command line
    parser.add_argument('--h-param', type=float, help="Override 'h' parameter in conf.yaml")
    parser.add_argument('--k-param', type=float, help="Override 'k' parameter in conf.yaml")
    parser.add_argument('--total-shots', type=int, help="Override 'total_shots' in conf.yaml") # Use int for shots
    # Allow running all generated configurations instead of just one
    parser.add_argument('--run-all-conf', action='store_true', help="Run all configurations generated by Conf.generate_all_confs()") # Changed to store_true

    args = parser.parse_args()

    # --- Configuration Loading ---
    confs = []
    if args.run_all_conf:
        # Generate multiple configurations based on ranges defined in Conf class
        confs = Conf.generate_all_confs()
        if not confs:
            print("Warning: generate_all_confs() returned no configurations. Check Conf class.")
            exit() # Exit if no configurations are generated
    else:
        # Load a single configuration, potentially overriding from CLI args
        conf = Conf() # Create default Conf instance
        try:
            conf.load() # Load parameters from conf.yaml
            print("Loaded configuration from conf.yaml")
        except FileNotFoundError:
            print("conf.yaml not found, using default Conf parameters.")
        except Exception as e:
            print(f"Error loading conf.yaml: {e}. Using default Conf parameters.")

        # Override specific parameters if provided via command line
        if args.h_param is not None: conf.h = args.h_param
        if args.k_param is not None: conf.k = args.k_param
        if args.total_shots is not None: conf.total_shots = args.total_shots
        confs.append(conf) # Add the single (potentially modified) config to the list

    print(f"Generated {len(confs)} configurations to run.")
    print_run_plan()
    input("Press Enter to continue...")

    # --- Observable Setup ---
    observable_factory = ObservableFactory()

    # --- Execution Loop ---
    # Group configurations by parameters that require backend re-initialization
    # For simplicity here, assume re-init for each conf, but could optimize
    current_runner = None

    for i, conf in enumerate(confs):
        print(f"\n--- Running Configuration {i+1}/{len(confs)} ---")
        print(conf) # Print current config

        # Create/get observables for this config (needed for runner)
        # Note: Factory creates *all* observables, runner uses the list of simulatable ones
        simulatable_obs_list = observable_factory.create_observables(conf)

        # Initialize Runner (or re-init if backend/noise changes significantly)
        # Pass only the list of observables to simulate
        runner = Runner(simulatable_obs_list)
        # Initialize backend, noise model etc. for this specific conf
        runner.init_run_level(conf, conf.backend)

        # Execute each observable for the current configuration
        for obs in simulatable_obs_list:
             runner.execute_observable(obs, conf, res)

        print(f"--- Finished Configuration {i+1}/{len(confs)} ---")


    # --- Post-Processing ---
    print("\n--- Post-Processing Results ---")
    res.process_results(observable_factory) # Calculate metrics, derive observables

    # --- Save Processed Results ---
    res.save_results("processed_results.json")

    # --- Analysis & Reporting ---
    print("\n--- Generating Plots and Report ---")
    # Load results back if needed (e.g., if running analysis separately)
    # res.load_results("processed_results.json")

    report_and_plot(res)
    print("\n--- Simulation and Analysis Complete ---")
